version: '3.8'
services:
  api-general:
    build:
      context: .
      dockerfile: ./configs/docker/Dockerfile.api-general
    ports:
      - '${NX_PUBLIC_BACK_GENERAL}:${NX_PUBLIC_BACK_GENERAL}'
    environment:
      - NODE_ENV=production
      - DATABASE_GENERAL_URL=${DATABASE_GENERAL_URL}
    env_file:
      - .env
    command: sh -c "npm run prisma:generate && npm run prisma:deploy && node /app/dist/main.js"

  api-pure-tv:
    build:
      context: .
      dockerfile: ./configs/docker/Dockerfile.api-pure-tv
    ports:
      - '${NX_PUBLIC_BACK_PURE_TV}:${NX_PUBLIC_BACK_PURE_TV}'
    environment:
      - NODE_ENV=production
      - DATABASE_GENERAL_URL=${DATABASE_GENERAL_URL}
    env_file:
      - .env
    command: sh -c "npm run prisma:generate && npm run prisma:deploy && node /app/dist/main.js"

  web-pure-tv:
    build:
      context: .
      dockerfile: ./configs/docker/Dockerfile.web-pure-tv
    ports:
      - '${NX_PUBLIC_FRONT_PURE_TV}:80'
    environment:
      - NODE_ENV=production
      - NX_PUBLIC_BACK_PURE_TV= ${NX_PUBLIC_BACK_PURE_TV}
      - NX_PUBLIC_BACK_GENERAL= ${NX_PUBLIC_BACK_GENERAL}
      - NX_PUBLIC_FRONT_PURE_TV= ${NX_PUBLIC_FRONT_PURE_TV}
