FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run prisma:generate
RUN npm run build:back-general

FROM node:18-alpine

WORKDIR /app


COPY --from=builder /app/dist/apps/api/api-general ./dist
COPY --from=builder /app/dist/libs ./dist
COPY --from=builder /app/package*.json ./

RUN npm install --production --ignore-scripts

EXPOSE ${PORT_GENERAL}

CMD ["node", "dist/main"]
