version: '3.8'
services:
  api-general:
    build:
      context: .
      dockerfile: Dockerfile.api-general
    ports:
      - '${PORT_GENERAL}:${PORT_GENERAL}'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    command: sh -c "npm run prisma:generate && npm run prisma:deploy && node /app/dist/main.js"
    depends_on:
      - postgres

  api-pure-tv:
    build:
      context: .
      dockerfile: Dockerfile.api-pure-tv
    ports:
      - '${PORT_BACK_PURE_TV}:${PORT_BACK_PURE_TV}'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    command: sh -c "npm run prisma:generate && npm run prisma:deploy && node /app/dist/main.js"
    depends_on:
      - postgres

  web-pure-tv:
    build:
      context: .
      dockerfile: Dockerfile.web-pure-tv
    ports:
      - '${PORT_FRONT_PURE_TV}:80'
    environment:
      NODE_ENV: production

  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - /postgres-data:/var/lib/postgresql/data
