FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build:front-pure-marketing

FROM nginx:alpine

COPY --from=builder /app/dist/apps/web/web-pure-marketing /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
